version: '3.8'

services:
  waza-app:
    build:
      context: ./waza-app
    container_name: waza-app
    ports:
      - "7000:8080"
    env_file:
      - ./waza-app/.env
    depends_on:
      - metrics-app

  metrics-app:
    build:
      context: ./metrics-app
    container_name: metrics-app
    ports:
      - "3000:3000"
    env_file:
      - ./metrics-app/.env
