version: '3.8'

services:
  blog-app:
    build:
      context: ./blog-app
    container_name: blog-app
    ports:
      - "7000:8080"
    env_file:
      - ./blog-app/.env
    depends_on:
      - metrics-backend

  metrics-backend:
    build:
      context: ./metrics-backend
    container_name: metrics-backend
    ports:
      - "3000:3000"
    env_file:
      - ./metrics-backend/.env
