apiVersion: apps/v1
kind: Deployment
metadata:
  name: waza-app
  labels:
    app: waza-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: waza-app
  template:
    metadata:
      labels:
        app: waza-app
    spec:
      containers:
        - name: waza-app
          image: kelomo2502/waza-app:v1
          ports:
            - containerPort: 8080
          envFrom:
            - secretRef:
                name: waza-app-secret
          env:
            - name: NODE_ENV
              value: "production"
